config/routes.rb
Rails.application.routes.draw do

  resources :listbooks
  resources :lists
  resources :authors
  resources :books
  resources :users
  resources :sessions

  get 'welcome/index' => 'welcome#index'
  get 'home' => 'welcome#index'
  get "signup" => "users#new", :as => "signup"
  get'login' => 'sessions#new'
  post 'login' => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"
  get 'dashboard/index'
  post 'addToList' => 'users#addToList', :as =>"addToList"
		

  root 'welcome#index'

end

app/models/list.rb
class List
  include Mongoid::Document
  
  belongs_to :user
  has_many :listbook
  
  field :title, type: String
  field :description, type: String
end  

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_user, :only => [:show]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    session[:current_list_id] = @list.id.to_s
    session[:current_list] = List.find(@list.id)
  end

  # POST /lists
  # POST /lists.json
  def create
    # @list = List.new(list_params)
    @list = @current_user.lists.build(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %> | 
<%= link_to 'Add books to this list', listbooks_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @current_user.lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @list.user.full_name %>
</p>

<p>
	<strong>Books:</strong>
</p>

<table border=1 cellpadding="3">
  <% if @list.listbook.empty? %>
  <tr><td>This list is empty</td></tr>
  <% else %>
  <tr>
    <th>Title</th>
     <th>Pages</th>
     <th>Isbn</th>
     <th>Genre</th>
     <th>Author</th>
  </tr>
  <% end %>
  <% @list.listbook.each do |listbook| %>
  <% @book = Book.find(listbook.book_id) %>
    <tr>
     <td><%= @book.title %></td>
      <td><%= @book.pages %></td>
      <td><%= @book.isbn %></td>
      <td><%= @book.genre %></td>
      <td><%= @book.author.full_name %></td>
    </tr>
    <% end %>

  </table>

  <br>

<%= link_to 'Back', lists_path %>

<style>
td, th {
  padding: 5px;
}
</style>