config/routes.rb
Rails.application.routes.draw do

  resources :listbooks
  resources :lists
  resources :authors
  resources :books
  resources :users
  resources :sessions

  get 'welcome/index' => 'welcome#index'
  get 'home' => 'welcome#index'
  get "signup" => "users#new", :as => "signup"
  get'login' => 'sessions#new'
  post 'login' => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"
  get 'dashboard/index'
  post 'addToList' => 'users#addToList', :as =>"addToList"
		

  root 'welcome#index'

end

app/models/listbook.rb
class Listbook
  include Mongoid::Document

  belongs_to :book
  belongs_to :list
end

app/controllers/listbooks_controller.rb
class ListbooksController < ApplicationController
  before_action :set_listbook, only: [:show, :edit, :update, :destroy]

  # GET /listbooks
  # GET /listbooks.json
  def index
    # @listbooks = Listbook.all
    # @listbook should be only the one that has been selected before
    @listbooks = Listbook.all
    @current_list_id = session[:current_list_id]
    @current_list = session[:current_list] #List.where(:id => session[:current_list_id])
  end

  # GET /listbooks/1
  # GET /listbooks/1.json
  def show
  end

  # GET /listbooks/new
  def new
    @listbook = Listbook.new
    @current_list_id = session[:current_list_id]
    @current_list = session[:current_list]
  end

  # GET /listbooks/1/edit
  def edit
  end

  # POST /listbooks
  # POST /listbooks.json
  def create
    @listbook = Listbook.new(listbook_params)
    @listbook.list_id = session[:current_list_id]

    respond_to do |format|
      if @listbook.save
        format.html { redirect_to @listbook, notice: 'Book successfully added.' }
        format.json { render :show, status: :created, location: @listbook }
      else
        format.html { render :new }
        format.json { render json: @listbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listbooks/1
  # PATCH/PUT /listbooks/1.json
  def update
    respond_to do |format|
      if @listbook.update(listbook_params)
        format.html { redirect_to @listbook, notice: 'Listbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @listbook }
      else
        format.html { render :edit }
        format.json { render json: @listbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listbooks/1
  # DELETE /listbooks/1.json
  def destroy
    @listbook.destroy
    respond_to do |format|
      format.html { redirect_to listbooks_url, notice: 'Book successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listbook
      @listbook = Listbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listbook_params
      #params[:listbook]
      params.require(:listbook).permit(:list_id, :book_id)
    end
end

app/helpers/listbooks_helper.rb
module ListbooksHelper
end

app/views/listbooks/_form.html.erb
<%= form_for(@listbook) do |f| %>
  <% if @listbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listbook.errors.count, "error") %> prohibited this listbook from being saved:</h2>

      <ul>
      <% @listbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Select Book" %><br>
    <%= f.select(:book_id, @current_user.books.collect {|book| [book.title, book.id]}) %>
    <br><br>
    <%#= f.hidden_field(:list_id, :value => @current_list_id) %>
  </div>

  <div class="actions">
    <%= f.submit "Add Book"%>
  </div>
          
<% end %>

app/views/listbooks/edit.html.erb
<h1>Editing Listbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @listbook %> |
<%= link_to 'Back', listbooks_path %>

app/views/listbooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books in "<%= @current_list["title"] %>" list </h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% a = 0 %>
    <% @listbooks.each do |listbook| %>
      <% if listbook.list_id.to_s == @current_list_id %>
      <% a = a + 1 %>
      <tr>
        <% mybook = Book.find(listbook.book_id) %>
        <td><%= mybook.title %></td>
        <td><%= link_to 'Remove', listbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
    <% if a == 0 %>
      <tr><td>This list is empty.</td></tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Book', new_listbook_path %>

app/views/listbooks/new.html.erb
<h1>Add a new book</h1>

<%= render 'form' %>

<%= link_to 'Back', listbooks_path %>

app/views/listbooks/show.html.erb
<p id="notice"><%= notice %></p>

<%#= link_to 'Edit', edit_listbook_path(@listbook) %>
<%= link_to 'Back', listbooks_path %>